exp_configuration={
        -6:{ # Negative Values for visualization experiments
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':40, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['ResNet18'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(0,0),#(25,25),
        'rand_azim':(0,0),
        'rand_angle':(0,0),
        'min_dist':1.2, 'rand_dist':0.,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':0,
        'rand_ambient_color':0.,
        'ambient_color':0.7,
        'rand_diffuse_color':0.,
        'diffuse_color':0.5

        ,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'save_img':True,
        'target_img_idx':[5,20,15,29,50],
        'comment':''
    },
     -5:{ # Negative Values for visualization experiments
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':40, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['ResNet18'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'blurred_image',
        'texture_type':'random_solid',
        'visualize':False,
        'save_img':True,
        'target_img_idx':[5,20,15,29,50],
        'comment':''
    },
     -4:{ # Negative Values for visualization experiments
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':40, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['ResNet18'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5, # 
        'source_3d_models':['pack','1ball','t_shirt','book'], #'pillow','cup','t_shirt','pack','1ball',
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':1.6, 'rand_dist':0.,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':0,
        'rand_ambient_color':0.0,
        'ambient_color':0.7,
        'rand_diffuse_color':0.0,
        'diffuse_color':0.4,
        'specular_color':0.0,
        'background_type':'custom',
        'texture_type':'random_solid',
        'visualize':False,
        'save_img':True,
        'target_img_idx':[1,2,3,4],
        'comment':''
    },
       -3:{ # Negative Values for visualization experiments
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':40, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5, # 
        'source_3d_models':['pillow'], #,'t_shirt','pack','1ball','book'
        'rand_elev':(35,35),
        'rand_azim':(20,20),
        'rand_angle':(15,15),
        'min_dist':1.2, 'rand_dist':0.,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'custom',
        'visualize':False,
        'save_img':True,
        'target_img_idx':[1,29],
        'comment':''
    },
       -2:{ # Negative Values for visualization experiments
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':40, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5, # 
        'source_3d_models':['pillow','cup'], #,'t_shirt','pack','1ball','book'
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':1.2, 'rand_dist':0.,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'save_img':True,
        'comment':''
    },
    -1:{ # Negative Values for visualization experiments
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':20, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5, # 
        'source_3d_models':['pillow','cup'], 
        'rand_elev':(-25,25),
        'rand_azim':(-25,25),
        'rand_angle':(-25,25),
        # 'rand_elev':(40,40),
        # 'rand_azim':(-70,-70),
        # 'rand_angle':(0,1),
        'min_dist':1.4, 'rand_dist':0.,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.,
        'ambient_color':0.6,
        'rand_diffuse_color':0.0,
        'diffuse_color':0.4,
        'specular_color':0.0,
        'background_type':'custom',
        'texture_type':'random_solid',
        'visualize':False,
        'save_img':True,
        'comment':''
    },
     0:{ # Snapshot models
        'p':0.7,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':60, # "max_iterations"
        'num_images':20,
        'source_model_names':['ResNet50','vgg16',  'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'RE_MI': 'OTM3','DI-MI': 'DTM3'},
        'shininess':0.5,
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'source_3d_models':['1ball','t_shirt','pack'],
        'rand_elev':(-30,30),
        'rand_azim':(-30,30),
        'rand_angle':(-30,1),
        'min_dist':1., 'rand_dist':0.,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':0,
        'rand_ambient_color':0.,
        'ambient_color':0.8,
        'rand_diffuse_color':0.0,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'visualize':True,
        'comment':''
    },
    ######################################
    # MAIN EXPERIMENT
    51:{  # PAPER Table 1
        'p':0.7,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'DI-MI-TI': 'DTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pack'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'none',
        'texture_type':'none',
        'comment':''
    },
       54:{  # PAPER Table 1
        'p':0.7,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'MI-TI': 'TM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pack'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'none',
        'texture_type':'none',
        'comment':''
    },
              58:{ 
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pack'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
    ############# 3D MODEL CHANGE
            64:{ # Paper Table 2
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['cup'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
                65:{
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
  66:{ 
        'p':1., 
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['t_shirt'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
    67:{
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['book'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
        68:{  # Paper Table 2
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['1ball'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    }, ####################################################################
      69:{ # Supp Table 2
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['2ball'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
      70:{  # Paper Table 3
        'p':1.,  # "prob f or DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['3ball'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },##################################################
      71:{  
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['4ball'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
    #  ATTA
   76:{ # Paper Table 1
        'p':0.7,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'MI-ATTA-TI': 'ATM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pack'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
    78:{
        # Probability test
        'p':0.7,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    }, #########################################################
    81:{ 
        # 25 degree
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-25,25),
        'rand_azim':(-25,25),
        'rand_angle':(-25,25),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
    82:{ 
        # 15 degree
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-15,15),
        'rand_azim':(-15,15),
        'rand_angle':(-15,15),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
    83:{
        # 5 degree
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-5,5),
        'rand_azim':(-5,5),
        'rand_angle':(-5,5),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
     84:{ 
        # 45 degree
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-45,45),
        'rand_azim':(-45,45),
        'rand_angle':(-45,45),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    }, ######################################################
      86:{ 
        # Decreased Rand dist
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':1.0, 'rand_dist':0.,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
     87:{
        # Decreased Rand dist
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.9, 'rand_dist':0.2,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
    88:{ 
        # Background
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_solid',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    }, #######################################
        89:{ 
        # Background
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_pixel',
        'visualize':False,
        'comment':'NEW'
    }, #####################################333
                91:{ 
        # Background
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'blurred_image',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },

                92:{ # Paper Table 1.
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'RDI-MI-TI': 'RTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'blurred_image',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    }, 
         96:{  # Paper Table 1.
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'RDI-MI-TI-VT': 'RTMV3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'blurred_image',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
          97:{  # Paper Table 1.
        'p':1.0,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'RDI-MI-TI-SI': 'RTMS3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'blurred_image',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    }, 
        100:{
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pack','pillow','book','1ball','t_shirt','cup'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':'All ensemble'
    },
      101:{ # BEST MODEL / WE PICK THIS AS MAIN MODEL
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pack','pillow','book'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':'3 model ensemble'
    },
     102:{ # BEST MODEL / WE PICK THIS AS MAIN MODEL
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI-VT': 'RTMV3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pack','pillow','book'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'random_pixel',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':'3 model ensemble'
    },
     105:{ # BEST MODEL / WE PICK THIS AS MAIN MODEL
        'p':1.,  # "prob for DI and RE"
        'alpha':2,
        'max_iterations':300, # "max_iterations"
        'num_images':1000,
        'source_model_names':['ResNet50','vgg16', 'DenseNet121', 'inception_v3'],
        'target_model_names':['vgg16','ResNet18', 'ResNet50', 'DenseNet121', 'inception_v3', 'inception_v4_timm', 'mobilenet_v2','inception_resnet_v2',  'adv_inception_v3', 'ens_adv_inception_resnet_v2'],
        'attack_methods': {'ODI-MI-TI': 'OTM3'},
        'number_of_v_samples':5,
        'number_of_si_scales':5,
        'shininess':0.5,
        'source_3d_models':['pillow'],
        'rand_elev':(-35,35),
        'rand_azim':(-35,35),
        'rand_angle':(-35,35),
        'min_dist':0.8, 'rand_dist':0.4,
        'light_location':[0.0, 0.0,4.0],
        'rand_light_location':4,
        'rand_ambient_color':0.3,
        'ambient_color':0.6,
        'rand_diffuse_color':0.5,
        'diffuse_color':0.0,
        'specular_color':0.0,
        'background_type':'none',
        'texture_type':'random_solid',
        'visualize':False,
        'comment':''
    },
}